In [1]:
import pandas as pd
import numpy as np

df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/test.csv')

In [2]:
df_test.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [3]:
df_test['Planet_Code'] = pd.factorize(df_test.HomePlanet)[0]
df_test['Planet_Code'] = df_test.Planet_Code.replace(-1, df_test['Planet_Code'].median())

df_test['CryoSleep_Code'] = pd.factorize(df_test.CryoSleep)[0]
df_test['Cabin_Code'] = pd.factorize(df_test.Cabin)[0]
df_test['Destination_Code'] = pd.factorize(df_test.Destination)[0]
df_test['VIP_Code'] = pd.factorize(df_test.VIP)[0]

df_test['CryoSleep_Code']= df_test.CryoSleep_Code.replace(-1, df_test['CryoSleep_Code'].median())
df_test['Cabin_Code'] = df_test.Cabin_Code.replace(-1, df_test['Cabin_Code'].median())
df_test['Destination_Code'] = df_test.Destination_Code.replace(-1, df_test['Destination_Code'].median())
df_test['VIP_Code'] = df_test.VIP_Code.replace(-1, df_test['VIP_Code'].median())

df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())
df_test['RoomService'] = df_test['RoomService'].fillna(df_test['RoomService'].median())
df_test['FoodCourt'] = df_test['FoodCourt'].fillna(df_test['FoodCourt'].median())
df_test['ShoppingMall'] = df_test['ShoppingMall'].fillna(df_test['ShoppingMall'].median())
df_test['Spa'] = df_test['Spa'].fillna(df_test['Spa'].median())
df_test['VRDeck']= df_test['VRDeck'].fillna(df_test['VRDeck'].median())

In [4]:
df_test.isnull().sum()

PassengerId           0
HomePlanet           87
CryoSleep            93
Cabin               100
Destination          92
Age                   0
VIP                  93
RoomService           0
FoodCourt             0
ShoppingMall          0
Spa                   0
VRDeck                0
Name                 94
Planet_Code           0
CryoSleep_Code        0
Cabin_Code            0
Destination_Code      0
VIP_Code              0
dtype: int64

In [5]:
df_test = df_test[['PassengerId','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Planet_Code','CryoSleep_Code','Cabin_Code','Destination_Code','VIP_Code']]
df_test

PassengerId   Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0        0013_01  27.0          0.0        0.0           0.0     0.0     0.0   
1        0018_01  19.0          0.0        9.0           0.0  2823.0     0.0   
2        0019_01  31.0          0.0        0.0           0.0     0.0     0.0   
3        0021_01  38.0          0.0     6652.0           0.0   181.0   585.0   
4        0023_01  20.0         10.0        0.0         635.0     0.0     0.0   
...          ...   ...          ...        ...           ...     ...     ...   
4272     9266_02  34.0          0.0        0.0           0.0     0.0     0.0   
4273     9269_01  42.0          0.0      847.0          17.0    10.0   144.0   
4274     9271_01  26.0          0.0        0.0           0.0     0.0     0.0   
4275     9273_01  26.0          0.0     2680.0           0.0     0.0   523.0   
4276     9277_01  43.0          0.0        0.0           0.0     0.0     0.0   

      Planet_Code  CryoSleep_Code  Cabin_Code  Destination_Code  VIP_Code  
0               0               0           0                 0         0  
1               0               1           1                 0         0  
2               1               0           2                 1         0  
3               1               1           3                 0         0  
4               0               1           4                 0         0  
...           ...             ...         ...               ...       ...  
4272            0               0        3261                 0         0  
4273            0               1        1576                 0         0  
4274            2               0        3262                 1         0  
4275            1               1        3263                 0         0  
4276            0               0        3264                 2         0  

[4277 rows x 12 columns]

In [6]:
df_test.isnull().sum()

PassengerId         0
Age                 0
RoomService         0
FoodCourt           0
ShoppingMall        0
Spa                 0
VRDeck              0
Planet_Code         0
CryoSleep_Code      0
Cabin_Code          0
Destination_Code    0
VIP_Code            0
dtype: int64

In [7]:
df_train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [8]:
df_train.Age.median()

27.0

In [9]:
# df_train.Age.median()
# df_train.HomePlanet.unique()
# df_train.CryoSleep.unique()
# df_train.Cabin.unique()
# df_train.Destination.unique()
# df_train.Age.unique()
# df_train.VIP.unique()
# df_train.RoomService.unique()
# df_train.FoodCourt.unique()
# df_train.ShoppingMall.unique()
# df_train.Spa.unique()
# df_train.VRDeck.unique()
# df_train.Name.unique()
# df_train.Transported.unique()
df_train['Planet_Code'] = pd.factorize(df_train.HomePlanet)[0]
df_train['Planet_Code'] = df_train.Planet_Code.replace(-1, df_train['Planet_Code'].median())

In [10]:
df_train['Planet_Code'].value_counts()

Planet_Code
1    4803
0    2131
2    1759
Name: count, dtype: int64

In [11]:
df_train['CryoSleep_Code'] = pd.factorize(df_train.CryoSleep)[0]
df_train['Cabin_Code'] = pd.factorize(df_train.Cabin)[0]
df_train['Destination_Code'] = pd.factorize(df_train.Destination)[0]
df_train['VIP_Code'] = pd.factorize(df_train.VIP)[0]

In [12]:
df_train['CryoSleep_Code']= df_train.CryoSleep_Code.replace(-1, df_test['CryoSleep_Code'].median())
df_train['Cabin_Code'] = df_train.Cabin_Code.replace(-1, df_test['Cabin_Code'].median())
df_train['Destination_Code'] = df_train.Destination_Code.replace(-1, df_test['Destination_Code'].median())
df_train['VIP_Code'] = df_train.VIP_Code.replace(-1, df_test['VIP_Code'].median())

In [13]:
df_train.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  Planet_Code  CryoSleep_Code  Cabin_Code  Destination_Code  \
0        False            0               0           0                 0   
1         True            1               0           1                 0   
2        False            0               0           2                 0   
3        False            0               0           2                 0   
4         True            1               0           3                 0   

   VIP_Code  
0         0  
1         0  
2         1  
3         0  
4         0

In [14]:
df_train['Age'] = df_train['Age'].fillna(df_test['Age'].median())
df_train['RoomService'] = df_train['RoomService'].fillna(df_test['RoomService'].median())
df_train['FoodCourt'] = df_train['FoodCourt'].fillna(df_test['FoodCourt'].median())
df_train['ShoppingMall']= df_train['ShoppingMall'].fillna(df_test['ShoppingMall'].median())
df_train['Spa'] = df_train['Spa'].fillna(df_test['Spa'].median())
df_train['VRDeck']= df_train['VRDeck'].fillna(df_test['VRDeck'].median())

In [15]:
df_train = df_train[['PassengerId','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Planet_Code','CryoSleep_Code','Cabin_Code','Destination_Code','VIP_Code','Transported']]
df_train

PassengerId   Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0        0001_01  39.0          0.0        0.0           0.0     0.0     0.0   
1        0002_01  24.0        109.0        9.0          25.0   549.0    44.0   
2        0003_01  58.0         43.0     3576.0           0.0  6715.0    49.0   
3        0003_02  33.0          0.0     1283.0         371.0  3329.0   193.0   
4        0004_01  16.0        303.0       70.0         151.0   565.0     2.0   
...          ...   ...          ...        ...           ...     ...     ...   
8688     9276_01  41.0          0.0     6819.0           0.0  1643.0    74.0   
8689     9278_01  18.0          0.0        0.0           0.0     0.0     0.0   
8690     9279_01  26.0          0.0        0.0        1872.0     1.0     0.0   
8691     9280_01  32.0          0.0     1049.0           0.0   353.0  3235.0   
8692     9280_02  44.0        126.0     4688.0           0.0     0.0    12.0   

      Planet_Code  CryoSleep_Code  Cabin_Code  Destination_Code  VIP_Code  \
0               0               0           0                 0         0   
1               1               0           1                 0         0   
2               0               0           2                 0         1   
3               0               0           2                 0         0   
4               1               0           3                 0         0   
...           ...             ...         ...               ...       ...   
8688            0               0        6556                 2         1   
8689            1               1        6557                 1         0   
8690            1               0        6558                 0         0   
8691            0               0        6559                 2         0   
8692            0               0        6559                 0         0   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 13 columns]

In [16]:
df_train.corr()

PassengerId       Age  RoomService  FoodCourt  ShoppingMall  \
PassengerId          1.000000 -0.008962     0.000375  -0.009200      0.017795   
Age                 -0.008962  1.000000     0.068731   0.127398      0.033308   
RoomService          0.000375  0.068731     1.000000  -0.015126      0.052337   
FoodCourt           -0.009200  0.127398    -0.015126   1.000000     -0.013717   
ShoppingMall         0.017795  0.033308     0.052337  -0.013717      1.000000   
Spa                 -0.005198  0.120861     0.009244   0.221468      0.014542   
VRDeck               0.015945  0.099597    -0.018624   0.224572     -0.007849   
Planet_Code         -0.008484 -0.130545     0.190514  -0.310342      0.080826   
CryoSleep_Code      -0.003709 -0.073654    -0.240750  -0.202675     -0.207213   
Cabin_Code           0.982097 -0.007093     0.000187  -0.009546      0.019412   
Destination_Code     0.003340  0.006853    -0.045733   0.111057     -0.024721   
VIP_Code             0.013608  0.092008     0.056566   0.125499      0.018412   
Transported          0.021491 -0.074213    -0.241124   0.045583      0.009391   

                       Spa    VRDeck  Planet_Code  CryoSleep_Code  Cabin_Code  \
PassengerId      -0.005198  0.015945    -0.008484       -0.003709    0.982097   
Age               0.120861  0.099597    -0.130545       -0.073654   -0.007093   
RoomService       0.009244 -0.018624     0.190514       -0.240750    0.000187   
FoodCourt         0.221468  0.224572    -0.310342       -0.202675   -0.009546   
ShoppingMall      0.014542 -0.007849     0.080826       -0.207213    0.019412   
Spa               1.000000  0.147658    -0.224423       -0.196893   -0.006893   
VRDeck            0.147658  1.000000    -0.249392       -0.190437    0.015028   
Planet_Code      -0.224423 -0.249392     1.000000       -0.041927   -0.007209   
CryoSleep_Code   -0.196893 -0.190437    -0.041927        1.000000   -0.006646   
Cabin_Code       -0.006893  0.015028    -0.007209       -0.006646    1.000000   
Destination_Code  0.055815  0.073293    -0.246953        0.094061    0.001982   
VIP_Code          0.060991  0.123061    -0.068536       -0.080247    0.011492   
Transported      -0.218545 -0.204874    -0.102240        0.451744    0.022355   

                  Destination_Code  VIP_Code  Transported  
PassengerId               0.003340  0.013608     0.021491  
Age                       0.006853  0.092008    -0.074213  
RoomService              -0.045733  0.056566    -0.241124  
FoodCourt                 0.111057  0.125499     0.045583  
ShoppingMall             -0.024721  0.018412     0.009391  
Spa                       0.055815  0.060991    -0.218545  
VRDeck                    0.073293  0.123061    -0.204874  
Planet_Code              -0.246953 -0.068536    -0.102240  
CryoSleep_Code            0.094061 -0.080247     0.451744  
Cabin_Code                0.001982  0.011492     0.022355  
Destination_Code          1.000000  0.044707     0.108152  
VIP_Code                  0.044707  1.000000    -0.037261  
Transported               0.108152 -0.037261     1.000000

In [17]:
from sklearn.model_selection import train_test_split

X = df_train.drop(columns='Transported')
y = df_train['Transported']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.767514813523876
Logistic Regression Confusion Matrix:
 [[ 898  526]
 [ 141 1304]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

       False       0.86      0.63      0.73      1424
        True       0.71      0.90      0.80      1445

    accuracy                           0.77      2869
   macro avg       0.79      0.77      0.76      2869
weighted avg       0.79      0.77      0.76      2869



/opt/miniconda3/envs/spaceship-titanic/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(criterion='gini', n_estimators=700,
                             min_samples_split=10, min_samples_leaf=1,
                             oob_score=True, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Random Forest Classification Report:\n", classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.7831997211571976
Random Forest Confusion Matrix:
 [[1095  329]
 [ 293 1152]]
Random Forest Classification Report:
               precision    recall  f1-score   support

       False       0.79      0.77      0.78      1424
        True       0.78      0.80      0.79      1445

    accuracy                           0.78      2869
   macro avg       0.78      0.78      0.78      2869
weighted avg       0.78      0.78      0.78      2869



In [20]:
from sklearn.svm import SVC, LinearSVC

svc_model = SVC()
svc_model.fit(X_train, y_train)
y_pred_svc = svc_model.predict(X_test)

print("SVC Accuracy:", accuracy_score(y_test, y_pred_svc))
print("SVC Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svc))
print("SVC Classification Report:\n", classification_report(y_test, y_pred_svc))

SVC Accuracy: 0.5507145346810736
SVC Confusion Matrix:
 [[869 555]
 [734 711]]
SVC Classification Report:
               precision    recall  f1-score   support

       False       0.54      0.61      0.57      1424
        True       0.56      0.49      0.52      1445

    accuracy                           0.55      2869
   macro avg       0.55      0.55      0.55      2869
weighted avg       0.55      0.55      0.55      2869



In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 4)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("KNN Classification Report:\n", classification_report(y_test, y_pred_knn))

KNN Accuracy: 0.6075287556639944
KNN Confusion Matrix:
 [[894 530]
 [596 849]]
KNN Classification Report:
               precision    recall  f1-score   support

       False       0.60      0.63      0.61      1424
        True       0.62      0.59      0.60      1445

    accuracy                           0.61      2869
   macro avg       0.61      0.61      0.61      2869
weighted avg       0.61      0.61      0.61      2869



In [22]:
from sklearn.naive_bayes import GaussianNB

gnb_model = GaussianNB()
gnb_model.fit(X_train, y_train)
y_pred_gnb = gnb_model.predict(X_test)

print("GaussianNB Accuracy:", accuracy_score(y_test, y_pred_gnb))
print("GaussianNB Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))
print("GaussianNB Classification Report:\n", classification_report(y_test, y_pred_gnb))

GaussianNB Accuracy: 0.6709654932032066
GaussianNB Confusion Matrix:
 [[ 551  873]
 [  71 1374]]
GaussianNB Classification Report:
               precision    recall  f1-score   support

       False       0.89      0.39      0.54      1424
        True       0.61      0.95      0.74      1445

    accuracy                           0.67      2869
   macro avg       0.75      0.67      0.64      2869
weighted avg       0.75      0.67      0.64      2869



In [23]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(criterion='gini', 
                                  min_samples_split=10, min_samples_leaf=1)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Decision Tree Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("Decision Tree Classification Report:\n", classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7333565702335308
Decision Tree Confusion Matrix:
 [[1058  366]
 [ 399 1046]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

       False       0.73      0.74      0.73      1424
        True       0.74      0.72      0.73      1445

    accuracy                           0.73      2869
   macro avg       0.73      0.73      0.73      2869
weighted avg       0.73      0.73      0.73      2869



In [24]:
from sklearn.ensemble import AdaBoostClassifier

ab_model = AdaBoostClassifier()
ab_model.fit(X_train, y_train)
y_pred_ab = ab_model.predict(X_test)

print("Ada Boost Accuracy:", accuracy_score(y_test, y_pred_ab))
print("Ada Boost Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ab))
print("Ada Boost Classification Report:\n", classification_report(y_test, y_pred_ab))

Ada Boost Accuracy: 0.7605437434646218
Ada Boost Confusion Matrix:
 [[1085  339]
 [ 348 1097]]
Ada Boost Classification Report:
               precision    recall  f1-score   support

       False       0.76      0.76      0.76      1424
        True       0.76      0.76      0.76      1445

    accuracy                           0.76      2869
   macro avg       0.76      0.76      0.76      2869
weighted avg       0.76      0.76      0.76      2869



In [25]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()
gb_model.fit(X_train, y_train)
y_pred_gb = gb_model.predict(X_test)

print("Gradient Boost Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Gradient Boost Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))
print("Gradient Boost Classification Report:\n", classification_report(y_test, y_pred_gb))

Gradient Boost Accuracy: 0.7859881491808993
Gradient Boost Confusion Matrix:
 [[1035  389]
 [ 225 1220]]
Gradient Boost Classification Report:
               precision    recall  f1-score   support

       False       0.82      0.73      0.77      1424
        True       0.76      0.84      0.80      1445

    accuracy                           0.79      2869
   macro avg       0.79      0.79      0.79      2869
weighted avg       0.79      0.79      0.79      2869



In [33]:
import optuna
from sklearn.ensemble import GradientBoostingClassifier

def objective(trial):
    loss=
    n_estimators = trial.suggest_int('n_estimators', 100, 400, step=50)
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.1, log=True)
    max_depth = trial.suggest_int('max_depth', 4, 8)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 100, 150)

    gb_model = GradientBoostingClassifier(
        loss="log_loss",
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )

    gb_model.fit(X_train, y_train)

    y_pred_gb = gb_model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred_gb)

    return accuracy

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

print("Best hyperparameters: ", study.best_params)
print("Best accuracy: ", study.best_value)

# Best score
modelf.best_score_

# Best Estimator
modelf.best_estimator_

[I 2025-02-05 20:32:21,552] A new study created in memory with name: no-name-52152460-cf75-4930-8e9f-84f916fed70a
[I 2025-02-05 20:32:25,219] Trial 0 finished with value: 0.7877309166957128 and parameters: {'n_estimators': 300, 'learning_rate': 0.024379111614175993, 'max_depth': 8, 'min_samples_leaf': 143}. Best is trial 0 with value: 0.7877309166957128.
[I 2025-02-05 20:32:28,211] Trial 1 finished with value: 0.7894736842105263 and parameters: {'n_estimators': 400, 'learning_rate': 0.028457691259623937, 'max_depth': 4, 'min_samples_leaf': 141}. Best is trial 1 with value: 0.7894736842105263.
[I 2025-02-05 20:32:30,725] Trial 2 finished with value: 0.7779714186127571 and parameters: {'n_estimators': 250, 'learning_rate': 0.0020034349051737447, 'max_depth': 6, 'min_samples_leaf': 122}. Best is trial 1 with value: 0.7894736842105263.
[I 2025-02-05 20:32:33,362] Trial 3 finished with value: 0.7866852561868247 and parameters: {'n_estimators': 250, 'learning_rate': 0.06263189127780579, 'max

Best hyperparameters:  {'n_estimators': 250, 'learning_rate': 0.023290466988450245, 'max_depth': 4, 'min_samples_leaf': 145}
Best accuracy:  0.7943534332520041


NameError: name 'modelf' is not defined

In [26]:
df_train_without_ids = df_train.drop('PassengerId', axis=1)
X = df_train_without_ids.drop(columns='Transported')
y = df_train_without_ids['Transported']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [27]:
df_train_without_ids.head()

Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Planet_Code  \
0  39.0          0.0        0.0           0.0     0.0     0.0            0   
1  24.0        109.0        9.0          25.0   549.0    44.0            1   
2  58.0         43.0     3576.0           0.0  6715.0    49.0            0   
3  33.0          0.0     1283.0         371.0  3329.0   193.0            0   
4  16.0        303.0       70.0         151.0   565.0     2.0            1   

   CryoSleep_Code  Cabin_Code  Destination_Code  VIP_Code  Transported  
0               0           0                 0         0        False  
1               0           1                 0         0         True  
2               0           2                 0         1        False  
3               0           2                 0         0        False  
4               0           3                 0         0         True

In [61]:
from xgboost import XGBClassifier

def objective_optuna(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 100, step=10)
    max_depth = trial.suggest_int('max_depth', 2, 4, 8)
    learning_rate = trial.suggest_float('learning_rate', 0.1, 1, log=True)
    objective = trial.suggest_categorical('objective', ['reg:squarederror', 'binary:logistic', 'binary:hinge'])

    xgb_model = XGBClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        learning_rate=learning_rate,
        objective=objective,
        random_state=42
    )
    xgb_model.fit(X_train, y_train)

    y_pred_xgb = xgb_model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred_xgb)

    return accuracy

study = optuna.create_study(direction='maximize')
study.optimize(objective_optuna, n_trials=100)

print("Best hyperparameters: ", study.best_params)
print("Best accuracy: ", study.best_value)

# Best score
modelf.best_score_

# Best Estimator
modelf.best_estimator_

[I 2025-02-05 20:49:39,434] A new study created in memory with name: no-name-5f6b2eb9-7d81-4bdb-8897-795d0147a5de
/var/folders/mz/90j2mwc116g4xxfj2_10f8b00000gn/T/ipykernel_1935/3294176097.py:5: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
  max_depth = trial.suggest_int('max_depth', 2, 4, 8)
/opt/miniconda3/envs/spaceship-titanic/lib/python3.12/site-packages/optuna/distributions.py:699: UserWarning: The distribution is specified by [2, 4] and step=8, but the range is not divisible by `step`. It will be replaced by [2, 2].
  warnings.warn(
[I 2025-02-05 20:49:39,507] Trial 0 finished with value: 0.7852910421749738 and parameters: {'n_estimators': 60, 'max_depth': 2, 'learning_rate': 0.43390865054152483, 'objective': 'reg:squarederror'}. Best is trial 0 with value: 0.7852910421749738.
/var/folders/mz/90j2mwc116g4xxfj2_10f8b00000gn/T/ipykernel_1935/3294176097.py:5: FutureWarning: suggest_int() got {'step'} as p

Best hyperparameters:  {'n_estimators': 80, 'max_depth': 2, 'learning_rate': 0.6520116579440337, 'objective': 'binary:logistic'}
Best accuracy:  0.7894736842105263


NameError: name 'modelf' is not defined